### ISSUE TITLE
Dynamically generated absolute URLs are broken

### ISSUE THREAD

**Issue by mnuzzolilo** [icflorescu/iisexpress-proxy#7] opened 2016-05-19 03:49 UTC
I have a method in my web app that builds absolute URLs (for assets).  Using this proxy causes all links generated by this method to fail (links are referencing the old localhost url instead of the one in the browser).  This would be great otherwise.

```
        public static string BuildAbsoluteURL(string virtualPath)
        {
            bool https = HttpContext.Current.Request.IsSecureConnection;
            if (!https)
            {
                var xproto = HttpContext.Current.Request.Headers["X-FORWARDED-PROTO"];
                if (xproto != null && xproto.ToLower() == "https")
                    https = true;
            }
            var absolutePathTarget = new Uri("http://" + HttpContext.Current.Request.Url.Authority + HttpContext.Current.Request.ApplicationPath.TrimEnd('/') + VirtualPathUtility.ToAbsolute(virtualPath, System.Web.HttpContext.Current.Request.ApplicationPath));
            var url = absolutePathTarget.ToString();
            if (https)
                url = "https://" + url.Substring("http://".Length);
            return url;
        }
```

**Comment by mnuzzolilo** [comment] 2016-05-19 03:52
Perhaps an approach to have a similar proxy in inverse, on the client machine, would fix this?

**Comment by icflorescu** [comment] 2016-05-19 19:40
I guess this is kind of an edge scenario, but it doesn't look like a bug in `iisexpress-proxy`.

Your server-side method generates URLs based on `HttpContext.Current.Request.Url.Authority` `HttpContext.Current.Request.ApplicationPath`. Can you please post a few sample URLs you're getting **with** and **without** using `iisexpress-proxy`?

**Comment by mnuzzolilo** [comment] 2016-05-19 21:01
The above method produces the same url with or without the proxy.  

example, if my website is hosted at localhost:1000, and my proxy allows the network to access 192.168.1.200:2000

above method produces: localhost:1000/Assets/foo.js

So on my macbook which is not hosting the site, I am going to 192.168.1.200:2000 but foo.js fails to load because it is trying to use localhost:1000/Assets/foo.js instead of 192.168.1.200:2000/Assets/foo.js

Only way I can see to fix this is to also have a similar proxy on my macbook, so that I can, on my macbook go to localhost:1000 and all traffic to that location is rerouted to 192.168.1.200. Do you know of a way I can do that?  Thank you.

**Comment by icflorescu** [comment] 2016-05-19 23:21
Oh, I see. Including the hostname in dynamically generated URLs is always going to be a problem.
Basically, this utility is working by convincing IISExpress that requests are coming from localhost, so your method will always put `localhost` in the generated URLs. I really can't think of a simple way to circumvent this...

I've intended `iisexpress-proxy` to be a quick-and-dirty solution for the simplest use cases, and yours is clearly not one of them :-). So maybe you should have a look at [browsersync.io](https://www.browsersync.io/). It's a nice, featured-packed utility I'm using for my own development workflow, since I've fully switched from .NET to Node.js. You can even tunnel your local server to public temporary subdomains on localtunnel.me and synchronize user actions across multiple devices...

**Comment by icflorescu** [comment] 2016-05-21 14:10
Going to close this now, since it's not a bug in `iisexpress-proxy`.

**Closed by icflorescu** 2016-05-21 14:10 UTC
