### ISSUE TITLE
Request requires localhost

### ISSUE THREAD

**Issue by FruitAndAShape** [icflorescu/iisexpress-proxy#11] opened 2017-01-11 14:32 UTC
Hi, the proxy forwards to 127.0.0.1 which results in a refused connection. I only seem to be able to request successfully from localhost. Why might this be?

**Comment by FruitAndAShape** [comment] 2017-01-11 14:53
oh, the code sets the domain as "localhost" but IIS is refusing the connection.

**Comment by srmrco** [comment] 2017-03-07 08:41
@FruitAndAShape I also noticed this. Take a look here https://github.com/icflorescu/iisexpress-proxy/issues/1#issuecomment-284655718

**Comment by icflorescu** [comment] 2018-06-05 15:40
Not a bug in `iisexpress-proxy`, so I'll be closing this.
Feel free to come up with a PR to address IPv6 connections, though ;-).

**Closed by icflorescu** 2018-06-05 15:40 UTC
